# hello-go-deploy-amazon-eks task-build-push.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: hello-go-deploy-amazon-eks

outputs:
- name: dist

run:
  path: ./hello-go-deploy-amazon-eks/ci/scripts/build-push.sh
  # args: [-debug]

